name: pipeline

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Install missing tools
        run: |
          sudo apt update
          sudo apt install git pandoc
          sudo snap install typst

      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Generate PDF
        run: |
          pandoc example.md --output=example.pdf --pdf-engine=typst

      - name: Upload PDF to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: example
          path: example.pdf

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload PDF to GCS
        run: |
          gsutil cp example.pdf gs://github-publishing-pipeline/example.pdf
